# Math memo
:sectnums:
:stem: latexmath
:toc:
:linkcss:

\( \def\b#1{\mathbf{#1}} \)
\( \def\ds{\displaystyle} \)
\( \def\txt#1{\ \textrm{#1} \ } \)

== if and only if

수학 영어 원서 책을 읽다 보면 _iff_ 라는 표현을 자주 접하게 되는데, 이 말은 __if and only
if__ 라는 말을 짧게 줄여서 쓴 표현이다.


=== 고등학교 학습 내용

이 표현의 의미를 설명하기에 앞서, 고등학교 때 배운 내용을 잠시 떠올려 보자. 우리는 다음의
두 수식은 같다고 배웠다.

[cols="2*^", options="header"]]
|===

| 수식
| 의미

| \( (P \to Q) \ \land \ (Q \to P) \) 
| if \(P\) then \(Q\) and if \(Q\) then \(P\)

| \( P = Q \)
| \(P\) is equal to \(Q\)

|===

즉, \( P \)가 \( Q \)의 필요 조건이자 충분 조건이면, \( P \) 와 \( Q \) 는 동치 관계라는
말이다.

이것을 다시 집합 기호를 빌려 표현하면, \( P \subset Q \) 이고, \( Q \subset P \) 이면, \(
P = Q \) 가 된다.


=== if and only if 의 의미

\( Q \txt{iff} P \) 는 \(Q\) if and only if \(P\) 와 같다고 이미 앞에서 이야기 했는데, 이
말은 결국 \( (P \to Q) \ \land \ (Q \to P) \) 와도 같은 표현이다. 어떻게 같게 되는지를
살펴 보자.


먼저 \(Q\) if and only if \(P\) 를 두 부분으로 나누어 보면 다음과 같이 된다.

[cols="2*^", options="header", width="70%"]
|===

| 의미
| 수식

| if \(P\) then \(Q\)   \( \quad (\leftarrow \)   \(Q\) if \(P)\)
| \( P \to Q \)

| only if \(P\) then \(Q\)   \( \quad (\leftarrow \)   \(Q\) only if \(P)\)
| \( Q \to P \)

|===

그런데 only if \(P\) then \(Q\) 부분이 어떻게 \( Q \to P \) 로 된다는 걸까? 직역하면
'오로지 \(P\)이면 \(Q\) 이다'가 되는데, 이것은 '\( P \to Q \)' 로 되는 것이 맞는 것이
아닌가 하는 생각이 들기 때문이다. 기존에는 이에 대한 설명이 없어서 내 나름대로 꽤
혼란스러웠던 기억이 나는데, 그 이유는 다음의 두 문장이 **등가**이기 때문이다.

* I cry, only if I'm sad. (나는 슬플 때에만 운다.)
+
(\(Q\) only if \(P\))

* If I cry, then I'm sad. (내가 울면 나는 슬프다.)
+
(\( Q \to P \))


=== 그림을 통한 이해

위의 예문을 아래의 그림을 통해 이해해 보자.

[cols="3*^", options="header"]]
|===

| (A)
| (B)
| pass:q[(C)]

| image:iff-1.svg[]
| image:iff-2.svg[]
.^| image:iff-3.svg[]

|===


* 그림 (A) 는 if \( P \) then \( Q \) 를 표시한다. 즉, \( P \) 는 슬픈 경우를, \( Q \) 는
  우는 경우를 표시한다. 그리고 보라색으로 표시된 \( R \) 부분은, 슬퍼서 우는 경우를 제외한
  모든 우는 경우, 즉 다시 말해서, 너무 기뻐서 울거나, 너무 아파서 울거나 또는 너무 분해서
  우는 경우 등등을 표시한다.

* 그림 (B) 는 only if \( P \) then \( Q \) 를 표시한다. 오로지 슬플 때에만 운다고
  함으로써, \( R \) 영역이 표시하고 있는 모든 경우를 \( Q \) 의 영역에서 배제하는 효과를
  가지게 된다. 결과적으로 \( Q \) 의 영역이 \( P \) 의 영역으로 축소되게 되는데, 이것을
  화살표로 표시하였다.

* 그림 pass:q[(C)] 는 최종적으로 \( P = Q \) 가 된 결과를 표시한다.


